import type { Material, InventoryLog, WarehouseLocation, WarehouseItem, Supplier, MaterialRequest, MaterialRequestItem } from "./types";

export const materials: Material[] = [
  {
    id: "mat-001",
    name: "Mỡ hàn Amtech 100g",
    nameEn: "Amtech Solder Paste 100g",
    code: "PM-MAT-2508-001",
    evnCode: "Chưa cấp",
    partNo: "NC-559-ASM",
    managementType: "Batch",
    category: "Vật tư tiêu hao",
    unit: "Hộp",
    status: "Mới",
    description: "Ghi chú cho mỡ hàn.",
    stock: 150,
    manufacturer: "AMTECH Inc.",
    origin: "USA",
    minStock: 10,
    maxStock: 200,
    technicalSpecs: [
      { property: "Trọng lượng", value: "100g" },
      { property: "Loại Flux", value: "No-Clean" },
      { property: "Nhiệt độ bảo quản", value: "20°C - 25°C" },
    ],
  },
  {
    id: "mat-002",
    name: "Gioăng đệm chịu nhiệt",
    code: "1.51.45.002.USA",
    partNo: "GASKET-XYZ",
    managementType: "Serial",
    category: "Phụ tùng",
    unit: "Cái",
    status: "Mới",
    description: "Gioăng đệm chịu nhiệt cho đường ống hơi.",
    stock: 88,
    minStock: 50,
    maxStock: 200,
  },
  {
    id: "mat-003",
    name: "Vòng bi SKF 6205",
    code: "1.51.45.003.USA",
    partNo: "SKF-6205",
    managementType: "Batch",
    category: "Vật tư tiêu hao",
    unit: "Cái",
    status: "Cũ nhưng dùng được",
    description: "Vòng bi cầu SKF 6205",
    stock: 20,
    minStock: 10,
    maxStock: 50,
  },
  {
    id: "mat-004",
    name: "Cáp điện 3 pha lõi đồng",
    code: "1.51.45.004.VN",
    partNo: "CADIVI-3P-CU",
    managementType: "Batch",
    category: "Vật tư tiêu hao",
    unit: "Mét",
    status: "Mới",
    description: "Cáp điện động lực 3 pha, lõi đồng, bọc PVC",
    stock: 120,
    minStock: 100,
    maxStock: 300,
  },
  {
    id: "mat-005",
    name: "Bơm nước ly tâm",
    code: "1.51.45.005.DE",
    partNo: "PUMP-W-100",
    managementType: "Serial",
    category: "Phụ tùng",
    unit: "Cái",
    status: "Hư hỏng",
    description: "Bơm nước ly tâm trục ngang, công suất 2.2kW",
    stock: 5,
    minStock: 2,
    maxStock: 10,
  },
  {
    id: "mat-006",
    name: "Van cầu DN50",
    code: "1.51.45.006.JP",
    partNo: "VALVE-DN50",
    managementType: "Serial",
    category: "Phụ tùng",
    unit: "Cái",
    status: "Mới",
    description: "Van cầu inox, nối bích, DN50 PN16",
    stock: 300,
    minStock: 100,
    maxStock: 500,
  },
  {
    id: "mat-007",
    name: "Dầu bôi trơn Shell",
    code: "PM-CHEM-001",
    partNo: "SHELL-TELLUS-S2",
    managementType: "Batch",
    category: "Hóa chất/Dầu mỡ",
    unit: "Lít",
    status: "Mới",
    description: "Dầu thủy lực Shell Tellus S2 MX 68",
    stock: 500,
    minStock: 200,
    maxStock: 1000,
  },
  {
    id: "mat-008",
    name: "Que hàn TIG 2.4mm",
    code: "PM-MAT-2509-001",
    partNo: "TIG-ROD-2.4",
    managementType: "Batch",
    category: "Vật tư tiêu hao",
    unit: "Kg",
    status: "Cũ nhưng dùng được",
    description: "Que hàn TIG inox 308L, đường kính 2.4mm",
    stock: 50,
    minStock: 20,
    maxStock: 100,
  },
  {
    id: "mat-009",
    name: "Bóng đèn LED Philips 12W",
    code: "PM-ELEC-01",
    partNo: "PHILIPS-LED-12W",
    managementType: "Batch",
    category: "Vật tư tiêu hao",
    unit: "Cái",
    status: "Mới",
    description: "Bóng đèn LED Bulb 12W, ánh sáng trắng",
    stock: 250,
    minStock: 100,
    maxStock: 500,
  },
  {
    id: "mat-010",
    name: "Găng tay bảo hộ",
    code: "PM-PPE-001",
    partNo: "SAFETY-GLOVE-01",
    managementType: "Batch",
    category: "BHLĐ",
    unit: "Đôi",
    status: "Mới",
    description: "Găng tay vải bảo hộ lao động",
    stock: 1000,
    minStock: 500,
    maxStock: 2000,
  },
  {
    id: "mat-011",
    name: "Aptomat 3P 100A",
    code: "PM-ELEC-02",
    partNo: "LS-MCCB-100A",
    managementType: "Serial",
    category: "Phụ tùng",
    unit: "Cái",
    status: "Hư hỏng không thể sửa chữa",
    description: "Aptomat khối 3P 100A, dòng cắt 25kA",
    stock: 45,
    minStock: 20,
    maxStock: 100,
  },
  {
    id: "mat-012",
    name: "Sơn chống rỉ",
    code: "PM-CHEM-002",
    partNo: "PAINT-RUST-01",
    managementType: "Batch",
    category: "Hóa chất/Dầu mỡ",
    unit: "Lít",
    status: "Mới",
    description: "Sơn lót chống rỉ màu xám, thùng 20L",
    stock: 80,
    minStock: 30,
    maxStock: 150,
  },
  {
    id: "mat-013",
    name: "Kính bảo hộ 3M",
    code: "PM-PPE-002",
    partNo: "3M-SF401AF",
    managementType: "Batch",
    category: "BHLĐ",
    unit: "Cái",
    status: "Mới",
    description: "Kính bảo hộ chống đọng sương 3M SF401AF",
    stock: 150,
    minStock: 50,
    maxStock: 300,
  },
  {
    id: "mat-014",
    name: "Đồng hồ đo áp suất",
    code: "PM-INST-001",
    partNo: "WIKA-232.50",
    managementType: "Serial",
    category: "Phụ tùng",
    unit: "Cái",
    status: "Thanh lý",
    description: "Đồng hồ đo áp suất WIKA, dải đo 0-10 bar",
    stock: 35,
    minStock: 15,
    maxStock: 50,
  },
  {
    id: "mat-015",
    name: "Khớp nối mềm cao su",
    code: "PM-MECH-001",
    partNo: "FLEX-JOINT-DN100",
    managementType: "Serial",
    category: "Phụ tùng",
    unit: "Cái",
    status: "Mới",
    description: "Khớp nối mềm cao su chống rung, nối bích DN100",
    stock: 22,
    minStock: 10,
    maxStock: 40,
  },
  {
    id: "mat-016",
    name: "Cảm biến nhiệt độ PT100",
    code: "PM-INST-002",
    partNo: "PT100-PROBE-100MM",
    managementType: "Serial",
    category: "Phụ tùng",
    unit: "Cái",
    status: "Cũ nhưng dùng được",
    description: "Cảm biến nhiệt độ loại PT100, 3 dây, dài 100mm",
    stock: 60,
    minStock: 30,
    maxStock: 100,
  },
  {
    id: "mat-017",
    name: "Dây thít nhựa",
    code: "PM-MAT-MISC-01",
    partNo: "CABLE-TIE-300",
    managementType: "Batch",
    category: "Vật tư tiêu hao",
    unit: "Bịch",
    status: "Mới",
    description: "Dây thít nhựa (lạt nhựa) dài 300mm, bịch 100 cái",
    stock: 400,
    minStock: 200,
    maxStock: 1000,
  },
  {
    id: "mat-018",
    name: "Pin PLC Mitsubishi",
    code: "PM-ELEC-03",
    partNo: "Q6BAT",
    managementType: "Batch",
    category: "Phụ tùng",
    unit: "Viên",
    status: "Mới",
    description: "Pin nuôi nguồn cho PLC Mitsubishi Q series",
    stock: 75,
    minStock: 50,
    maxStock: 150,
  },
  {
    id: "mat-019",
    name: "Khăn lau công nghiệp",
    code: "PM-MAT-MISC-02",
    partNo: "WIPE-01",
    managementType: "Batch",
    category: "Vật tư tiêu hao",
    unit: "Kg",
    status: "Mới",
    description: "Khăn lau, giẻ lau công nghiệp",
    stock: 120,
    minStock: 50,
    maxStock: 200,
  },
  {
    id: "mat-020",
    name: "Bộ lọc khí nén",
    code: "PM-MECH-002",
    partNo: "SMC-AF40-04",
    managementType: "Serial",
    category: "Phụ tùng",
    unit: "Bộ",
    status: "Hư hỏng",
    description: "Bộ lọc khí nén SMC, ren 1/2''",
    stock: 15,
    minStock: 5,
    maxStock: 25,
  },
  {
    id: "mat-021",
    name: "Dây curoa Bando B-60",
    code: "PM-MECH-003",
    partNo: "BANDO-B60",
    managementType: "Batch",
    category: "Phụ tùng",
    unit: "Sợi",
    status: "Cũ nhưng dùng được",
    description: "Dây curoa thang Bando bản B, chu vi 60 inch",
    stock: 90,
    minStock: 40,
    maxStock: 200,
  },
  {
    id: "mat-022",
    name: "Tua vít cách điện",
    code: "PM-TOOL-001",
    partNo: "WIHA-320N",
    managementType: "Batch",
    category: "Dụng cụ",
    unit: "Cái",
    status: "Mới",
    description: "Bộ tua vít cách điện 1000V Wiha",
    stock: 18,
    minStock: 10,
    maxStock: 30,
  },
  {
    id: "mat-023",
    name: "Mặt nạ phòng độc 3M",
    code: "PM-PPE-003",
    partNo: "3M-6200",
    managementType: "Batch",
    category: "BHLĐ",
    unit: "Cái",
    status: "Mới",
    description: "Mặt nạ phòng độc nửa mặt 3M 6200",
    stock: 40,
    minStock: 20,
    maxStock: 80,
  },
  {
    id: "mat-024",
    name: "Relay trung gian Omron",
    code: "PM-ELEC-04",
    partNo: "OMRON-MY4N-AC220",
    managementType: "Batch",
    category: "Phụ tùng",
    unit: "Cái",
    status: "Mới",
    description: "Relay trung gian Omron 14 chân, 220VAC",
    stock: 300,
    minStock: 100,
    maxStock: 500,
  },
  {
    id: "mat-025",
    name: "Ống đồng điều hòa",
    code: "PM-MAT-HVAC-01",
    partNo: "COPPER-TUBE-10MM",
    managementType: "Batch",
    category: "Vật tư tiêu hao",
    unit: "Mét",
    status: "Cũ nhưng dùng được",
    description: "Ống đồng cho máy lạnh, đường kính 10mm",
    stock: 85,
    minStock: 50,
    maxStock: 200,
  },
];


export const inventoryLogs: InventoryLog[] = [
  {
    id: "log-001",
    materialId: "mat-001",
    materialName: "Mỡ hàn Amtech 100g",
    quantity: 500,
    type: "inbound",
    date: "2024-07-20",
    actor: "Vinacomin",
  },
  {
    id: "log-002",
    materialId: "mat-003",
    materialName: "Vòng bi SKF 6205",
    quantity: 100,
    type: "inbound",
    date: "2024-07-19",
    actor: "Công ty TNHH BMT",
  },
  {
    id: "log-003",
    materialId: "mat-002",
    materialName: "Gioăng đệm chịu nhiệt",
    quantity: 2000,
    type: "outbound",
    date: "2024-07-21",
    actor: "Phân xưởng vận hành lò",
  },
  {
    id: "log-004",
    materialId: "mat-004",
    materialName: "Cáp điện 3 pha lõi đồng",
    quantity: 200,
    type: "outbound",
    date: "2024-07-22",
    actor: "Đội bảo trì điện",
  },
  {
    id: "log-005",
    materialId: "mat-005",
    materialName: "Bơm nước ly tâm",
    quantity: 2,
    type: "inbound",
    date: "2024-07-18",
    actor: "Nhà cung cấp ABC",
  },
  {
    id: "log-006",
    materialId: "mat-007",
    materialName: "Dầu bôi trơn Shell",
    quantity: 50,
    type: "outbound",
    date: "2024-07-23",
    actor: "Phân xưởng cơ khí",
  },
  {
    id: "log-007",
    materialId: "mat-006",
    materialName: "Van cầu DN50",
    quantity: 20,
    type: "inbound",
    date: "2024-07-20",
    actor: "Công ty XYZ",
  },
  {
    id: "log-008",
    materialId: "mat-003",
    materialName: "Vòng bi SKF 6205",
    quantity: 10,
    type: "outbound",
    date: "2024-07-24",
    actor: "Đội sửa chữa",
  },
];

const warehouseItems1: WarehouseItem[] = [
  {
    materialId: "mat-001",
    materialCode: "PM-MAT-2508-001",
    materialName: "Mỡ hàn Amtech 100g",
    quantity: 50,
    unit: "Hộp",
    batchSerial: "BATCH-20240701",
  },
  {
    materialId: "mat-002",
    materialCode: "1.51.45.002.USA",
    materialName: "Gioăng đệm chịu nhiệt",
    quantity: 30,
    unit: "Cái",
    batchSerial: "SN-Gasket-12345",
  },
];

const warehouseItems2: WarehouseItem[] = [
    {
    materialId: "mat-004",
    materialCode: "1.51.45.004.VN",
    materialName: "Cáp điện 3 pha lõi đồng",
    quantity: 100,
    unit: "Mét",
    batchSerial: "BATCH-CABLE-01",
  },
   {
    materialId: "mat-005",
    materialCode: "1.51.45.005.DE",
    materialName: "Bơm nước ly tâm",
    quantity: 2,
    unit: "Cái",
    batchSerial: "SN-PUMP-98765",
  },
];


export const warehouseLocations: WarehouseLocation[] = [
  { id: 'wh-1', code: 'A1-01-01', name: 'Kệ 01 - Tầng 1 - Dãy A', area: 'Khu A', type: 'Kệ Pallet', status: 'Active', barcode: 'LOC-A10101', maxWeight: 2000, dimensions: '2.7m x 1.2m', items: warehouseItems1 },
  { id: 'wh-2', code: 'A1-01-02', name: 'Kệ 01 - Tầng 2 - Dãy A', area: 'Khu A', type: 'Kệ Pallet', status: 'Active', items: warehouseItems2 },
  { id: 'wh-3', code: 'A1-01-03', name: 'Kệ 01 - Tầng 3 - Dãy A', area: 'Khu A', type: 'Kệ Pallet', status: 'Active', items: [] },
  { id: 'wh-4', code: 'A1-02-01', name: 'Kệ 02 - Tầng 1 - Dãy A', area: 'Khu A', type: 'Kệ Pallet', status: 'Inactive', items: [] },
  { id: 'wh-5', code: 'A1-02-02', name: 'Kệ 02 - Tầng 2 - Dãy A', area: 'Khu A', type: 'Kệ Pallet', status: 'Active', items: [] },
  { id: 'wh-6', code: 'B1-01-01', name: 'Kệ 01 - Tầng 1 - Dãy B', area: 'Khu B', type: 'Kệ Trung Tải', status: 'Active', items: [] },
  { id: 'wh-7', code: 'B1-01-02', name: 'Kệ 01 - Tầng 2 - Dãy B', area: 'Khu B', type: 'Kệ Trung Tải', status: 'Active', items: [] },
  { id: 'wh-8', code: 'B1-02-01', name: 'Kệ 02 - Tầng 1 - Dãy B', area: 'Khu B', type: 'Kệ Trung Tải', status: 'Active', items: [] },
  { id: 'wh-9', code: 'B1-02-02', name: 'Kệ 02 - Tầng 2 - Dãy B', area: 'Khu B', type: 'Kệ Trung Tải', status: 'Inactive', items: [] },
  { id: 'wh-10', code: 'CL-01-01', name: 'Kệ 01 - Kho Lạnh', area: 'Kho Lạnh', type: 'Kệ Pallet', status: 'Active', items: [] },
  { id: 'wh-11', code: 'CL-01-02', name: 'Kệ 02 - Kho Lạnh', area: 'Kho Lạnh', type: 'Kệ Pallet', status: 'Active', items: [] },
  { id: 'wh-12', code: 'CH-01', name: 'Sàn 01 - Kho Hóa chất', area: 'Kho Hóa chất', type: 'Sàn', status: 'Active', items: [] },
  { id: 'wh-13', code: 'CH-02', name: 'Sàn 02 - Kho Hóa chất', area: 'Kho Hóa chất', type: 'Sàn', status: 'Active', items: [] },
  { id: 'wh-14', code: 'A2-01-01', name: 'Kệ 01 - Tầng 1 - Dãy A2', area: 'Khu A', type: 'Kệ Pallet', status: 'Active', items: [] },
  { id: 'wh-15', code: 'A2-01-02', name: 'Kệ 01 - Tầng 2 - Dãy A2', area: 'Khu A', type: 'Kệ Pallet', status: 'Active', items: [] },
  { id: 'wh-16', code: 'A2-02-01', name: 'Kệ 02 - Tầng 1 - Dãy A2', area: 'Khu A', type: 'Kệ Pallet', status: 'Active', items: [] },
  { id: 'wh-17', code: 'A2-02-02', name: 'Kệ 02 - Tầng 2 - Dãy A2', area: 'Khu A', type: 'Kệ Pallet', status: 'Active', items: [] },
  { id: 'wh-18', code: 'B2-01-01', name: 'Kệ 01 - Tầng 1 - Dãy B2', area: 'Khu B', type: 'Kệ Trung Tải', status: 'Active', items: [] },
  { id: 'wh-19', code: 'B2-01-02', name: 'Kệ 01 - Tầng 2 - Dãy B2', area: 'Khu B', type: 'Kệ Trung Tải', status: 'Active', items: [] },
  { id: 'wh-20', code: 'B2-02-01', name: 'Kệ 02 - Tầng 1 - Dãy B2', area: 'Khu B', type: 'Kệ Trung Tải', status: 'Active', items: [] },
  { id: 'wh-21', code: 'A3-01-01', name: 'Kệ 01 - Tầng 1 - Dãy A3', area: 'Khu A', type: 'Kệ Pallet', status: 'Active', items: [] },
  { id: 'wh-22', code: 'A3-01-02', name: 'Kệ 01 - Tầng 2 - Dãy A3', area: 'Khu A', type: 'Kệ Pallet', status: 'Inactive', items: [] },
  { id: 'wh-23', code: 'C1-01', name: 'Vị trí sàn C1', area: 'Khu C', type: 'Sàn', status: 'Active', items: [] },
  { id: 'wh-24', code: 'C1-02', name: 'Vị trí sàn C2', area: 'Khu C', type: 'Sàn', status: 'Active', items: [] },
  { id: 'wh-25', code: 'B3-01-01', name: 'Kệ 01 - Tầng 1 - Dãy B3', area: 'Khu B', type: 'Kệ Trung Tải', status: 'Active', items: [] },
];

export const suppliers: Supplier[] = [
  { 
    id: 'sup-1', 
    code: 'NCC-001', 
    taxCode: '0101234567',
    name: 'Siemens Energy Vietnam', 
    address: 'Deutsches Haus, TP.HCM',
    country: 'Vietnam',
    type: 'OEM',
    paymentTerm: 'Net 30',
    currency: 'VND',
    status: 'Active',
    contacts: [
      { id: 'cont-1-1', name: 'Mr. John', position: 'Sales Mgr', email: 'john@siemens.com', phone: '+84 909 123 456' },
      { id: 'cont-1-2', name: 'Ms. Anna', position: 'Tech Support', email: 'anna@siemens.com', phone: '+84 918 654 321' },
    ]
  },
  { 
    id: 'sup-2', 
    code: 'NCC-002', 
    taxCode: '0300123456',
    name: 'General Electric', 
    address: 'New York, USA',
    country: 'USA',
    type: 'Manufacturer',
    paymentTerm: 'Net 60',
    currency: 'USD',
    status: 'Active',
    contacts: [] 
  },
  { 
    id: 'sup-3', 
    code: 'NCC-003', 
    taxCode: '0101234568',
    name: 'ABB', 
    address: 'Zurich, Switzerland',
    country: 'Switzerland',
    type: 'OEM',
    paymentTerm: 'Net 30',
    currency: 'EUR',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-4', 
    code: 'NCC-004', 
    taxCode: '0300123457',
    name: 'Công ty TNHH BMT', 
    address: 'Hanoi, Vietnam',
    country: 'Vietnam',
    type: 'Distributor',
    paymentTerm: 'COD',
    currency: 'VND',
    status: 'Inactive',
    contacts: []
  },
  { 
    id: 'sup-5', 
    code: 'NCC-005', 
    taxCode: '0101234569',
    name: 'Schneider Electric', 
    address: 'Paris, France',
    country: 'France',
    type: 'Manufacturer',
    paymentTerm: 'Net 45',
    currency: 'EUR',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-6', 
    code: 'NCC-006', 
    taxCode: '0300123458',
    name: 'Honeywell Vietnam', 
    address: 'Ho Chi Minh City, Vietnam',
    country: 'Vietnam',
    type: 'Distributor',
    paymentTerm: 'Net 30',
    currency: 'VND',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-7', 
    code: 'NCC-007', 
    taxCode: '0101234570',
    name: 'Rockwell Automation', 
    address: 'Milwaukee, USA',
    country: 'USA',
    type: 'Manufacturer',
    paymentTerm: 'Net 60',
    currency: 'USD',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-8', 
    code: 'NCC-008', 
    taxCode: '0300123459',
    name: 'Mitsubishi Electric', 
    address: 'Tokyo, Japan',
    country: 'Japan',
    type: 'OEM',
    paymentTerm: 'Net 30',
    currency: 'JPY',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-9', 
    code: 'NCC-009', 
    taxCode: '0101234571',
    name: 'Emerson Electric', 
    address: 'St. Louis, USA',
    country: 'USA',
    type: 'Manufacturer',
    paymentTerm: 'Net 60',
    currency: 'USD',
    status: 'Inactive',
    contacts: []
  },
  { 
    id: 'sup-10', 
    code: 'NCC-010', 
    taxCode: '0300123460',
    name: 'Bosch Rexroth', 
    address: 'Lohr am Main, Germany',
    country: 'Germany',
    type: 'OEM',
    paymentTerm: 'Net 30',
    currency: 'EUR',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-11', 
    code: 'NCC-011', 
    taxCode: '0101234572',
    name: 'Yokogawa Electric', 
    address: 'Tokyo, Japan',
    country: 'Japan',
    type: 'Manufacturer',
    paymentTerm: 'Net 45',
    currency: 'JPY',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-12', 
    code: 'NCC-012', 
    taxCode: '0300123461',
    name: 'Danfoss', 
    address: 'Nordborg, Denmark',
    country: 'Denmark',
    type: 'Manufacturer',
    paymentTerm: 'Net 30',
    currency: 'EUR',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-13', 
    code: 'NCC-013', 
    taxCode: '0101234573',
    name: 'Parker Hannifin', 
    address: 'Cleveland, USA',
    country: 'USA',
    type: 'Manufacturer',
    paymentTerm: 'Net 60',
    currency: 'USD',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-14', 
    code: 'NCC-014', 
    taxCode: '0300123462',
    name: 'Festo', 
    address: 'Esslingen, Germany',
    country: 'Germany',
    type: 'OEM',
    paymentTerm: 'Net 30',
    currency: 'EUR',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-15', 
    code: 'NCC-015', 
    taxCode: '0101234574',
    name: 'SMC Corporation', 
    address: 'Tokyo, Japan',
    country: 'Japan',
    type: 'Manufacturer',
    paymentTerm: 'Net 30',
    currency: 'JPY',
    status: 'Inactive',
    contacts: []
  },
  { 
    id: 'sup-16', 
    code: 'NCC-016', 
    taxCode: '0300123463',
    name: 'Endress+Hauser', 
    address: 'Reinach, Switzerland',
    country: 'Switzerland',
    type: 'OEM',
    paymentTerm: 'Net 45',
    currency: 'CHF',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-17', 
    code: 'NCC-017', 
    taxCode: '0101234575',
    name: 'WIKA Alexander Wiegand', 
    address: 'Klingenberg, Germany',
    country: 'Germany',
    type: 'Manufacturer',
    paymentTerm: 'Net 30',
    currency: 'EUR',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-18', 
    code: 'NCC-018', 
    taxCode: '0300123464',
    name: 'Phoenix Contact', 
    address: 'Blomberg, Germany',
    country: 'Germany',
    type: 'Manufacturer',
    paymentTerm: 'Net 30',
    currency: 'EUR',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-19', 
    code: 'NCC-019', 
    taxCode: '0101234576',
    name: 'Weidmüller', 
    address: 'Detmold, Germany',
    country: 'Germany',
    type: 'Manufacturer',
    paymentTerm: 'Net 30',
    currency: 'EUR',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-20', 
    code: 'NCC-020', 
    taxCode: '0300123465',
    name: 'OMRON Corporation', 
    address: 'Kyoto, Japan',
    country: 'Japan',
    type: 'OEM',
    paymentTerm: 'Net 45',
    currency: 'JPY',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-21', 
    code: 'NCC-021', 
    taxCode: '0101234577',
    name: 'Pilz GmbH & Co. KG', 
    address: 'Ostfildern, Germany',
    country: 'Germany',
    type: 'OEM',
    paymentTerm: 'Net 30',
    currency: 'EUR',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-22', 
    code: 'NCC-022', 
    taxCode: '0300123466',
    name: 'IFM Electronic', 
    address: 'Essen, Germany',
    country: 'Germany',
    type: 'Manufacturer',
    paymentTerm: 'Net 30',
    currency: 'EUR',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-23', 
    code: 'NCC-023', 
    taxCode: '0101234578',
    name: 'Pepperl+Fuchs', 
    address: 'Mannheim, Germany',
    country: 'Germany',
    type: 'Manufacturer',
    paymentTerm: 'Net 30',
    currency: 'EUR',
    status: 'Active',
    contacts: []
  },
  { 
    id: 'sup-24', 
    code: 'NCC-024', 
    taxCode: '0300123467',
    name: 'Turck', 
    address: 'Mülheim, Germany',
    country: 'Germany',
    type: 'Manufacturer',
    paymentTerm: 'Net 30',
    currency: 'EUR',
    status: 'Inactive',
    contacts: []
  },
  { 
    id: 'sup-25', 
    code: 'NCC-025', 
    taxCode: '0101234579',
    name: 'Balluff', 
    address: 'Neuhausen, Germany',
    country: 'Germany',
    type: 'OEM',
    paymentTerm: 'Net 30',
    currency: 'EUR',
    status: 'Active',
    contacts: []
  }
];

export const materialRequests: MaterialRequest[] = Array.from({ length: 25 }, (_, i) => {
    const id = i + 1;
    const priority = id % 3 === 0 ? 'Khẩn cấp' : 'Bình thường';
    const status = id % 2 === 0 ? 'Đã duyệt' : 'Chờ duyệt';
    const dept = id % 4 === 0 ? 'PX Vận hành 2' : id % 4 === 1 ? 'PX Sửa chữa' : id % 4 === 2 ? 'PX Hóa' : 'PX Vận hành 1';
    
    const requestItems: MaterialRequestItem[] = [
        {
            materialId: 'mat-007',
            materialCode: 'PM-CHEM-001',
            materialName: 'Dầu bôi trơn Shell',
            partNumber: 'SHELL-TELLUS-S2',
            unit: 'Lít',
            requestedQuantity: 5,
            stock: 500,
            notes: 'Thay dầu định kỳ'
        },
        {
            materialId: 'mat-002',
            materialCode: '1.51.45.002.USA',
            materialName: 'Gioăng đệm chịu nhiệt',
            partNumber: 'GASKET-XYZ',
            unit: 'Cái',
            requestedQuantity: 10,
            stock: 88,
            notes: 'Dự phòng rò rỉ'
        },
        {
            materialId: 'mat-004',
            materialCode: '1.51.45.004.VN',
            materialName: 'Lọc khí nạp',
            partNumber: 'CADIVI-3P-CU',
            unit: 'Bộ',
            requestedQuantity: 2,
            stock: 120,
            notes: 'Thay thế lọc bẩn'
        }
    ];

    return {
        id: `YCVT-2025-${String(id).padStart(3, '0')}`,
        requesterName: 'Nguyễn Văn A',
        requesterDept: dept,
        reason: `Cấp vật tư thay thế định kỳ Tổ máy GT${id} (Lọc khí, Gioăng)`,
        requestDate: new Date(2025, 7, id).toISOString(),
        priority: priority,
        status: status,
        workOrder: `WO-2025-${String(id + 98).padStart(3, '0')}`,
        approver: status === 'Đã duyệt' ? 'Lê Văn Kỹ (P.Kỹ thuật)' : undefined,
        items: requestItems
    };
});


export const getMaterials = async (): Promise<Material[]> => {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 100));
  // sort by code
  return [...materials].sort((a, b) => a.code.localeCompare(b.code));
};

export const getInventoryLogs = async (): Promise<InventoryLog[]> => {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 100));
  return inventoryLogs;
};

export const getWarehouseLocations = async (): Promise<WarehouseLocation[]> => {
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 100));
  return warehouseLocations;
};

export const getSuppliers = async (): Promise<Supplier[]> => {
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 100));
  return suppliers;
};

export const getMaterialRequests = async (): Promise<MaterialRequest[]> => {
    await new Promise(resolve => setTimeout(resolve, 100));
    return materialRequests.sort((a, b) => b.id.localeCompare(a.id));
}
